### ISSUE TITLE
Question about positioning entities.

### ISSUE THREAD

**Issue by Reffler** [Altanis/kinetics#19]
Hey, I would first like to sincerely thank you for developing this library. It has been amazing tampering around with it regardless of my limited coding knowledge. 

I have managed to create a very simple system which spawns a controllable square that can collide with a triangle. I am sure there may be other problems with my current approach but here comes my question:

How do I determine where to position the square or triangle? I have tried using the position property but have failed tremendously.

Here is my current code:

`const { System, Entity, Vector, Movement } = Kinetics;
const system = new System({
  tickRate: 60,
  friction: 0.1,
  gravity: 0,
  collisionInfo: { cellSize: 6 },
  render: {
    canvas: document.getElementById('gameCanvas'),
    hooks: {
      postRender: function () {
        const movements = Array.from(keys).map(key => {
          switch (key) {
            case 'KeyW': return Movement.Up;
            case 'KeyS': return Movement.Down;
            case 'KeyA': return Movement.Left;
            case 'KeyD': return Movement.Right;
          }
        })
        square1.move(...movements);
      }
    }
  }
});

function createEntity(vertices, mass, speed, system) {
  const entity = new Entity({
    form: { vertices },
    mass: mass,
    speed: speed,
  }, system);

  system.addEntity(entity);
  return entity;
}

const squareVertices = [
  new Vector(-20, -20),
  new Vector(-20, 20),
  new Vector(20, 20),
  new Vector(20, -20)
];

const triangleVertices = [
  new Vector(-20, -20),
  new Vector(0, 20),
  new Vector(20, -20)
];

const square1 = createEntity(squareVertices, 10, 1, system); // Mass, speed, etc...
const triangle1 = createEntity(triangleVertices, 10, 1, system); // Mass, speed, etc...

const keys = new Set();

document.addEventListener("keydown", (event) => keys.add(event.code));
document.addEventListener("keyup", (event) => keys.delete(event.code));`

**Comment by Altanis** [comment]
Hey there, thanks for using my library! If you want to manually set the position of an entity, you can modify the `position` property as such:

```js
entity.position = new Vector(29922, 2929);
// alternatively
entity.position.x = 2; entity.position.y = 20;
```

Let me know if you have any other problems. Cheers!

**Comment by Reffler** [comment]
Thanks! :) I managed to make it work!
