### ISSUE TITLE
Are the physics calculations decoupled?

### ISSUE THREAD

**Issue by Reffler** [Altanis/kinetics#20]
I know it might be inconvenient to keep asking questions here, but I have one last problem with my project I can't seem to fix. After reading through the documentation I can't tell if the physics engine is able to update the state of the entities without the need to render them. 

I coded a separate canvas which renders the entities differently with WebGL (by using pixi.js). Both canvases are running at the same time, with the first rendering the default Kinetics shapes and the second the WebGL shapes overlapped on top of the first. The WebGL shapes follow the rotation and position of the Kinetics shapes, and the system works perfectly. The only concern I have is the optimization, which should be improved by only rendering the second canvas, hence my question. I can of course provide my code if requested. 

After reading the documentation I attempted using `system.renderer = null`, but with no success. Would this be possible?

I am sure it would be possible for one to know this, but I am not the most experienced programmer right now lol,

Thank you for creating this.

**Comment by Altanis** [comment]
https://github.com/Altanis/kinetics/blob/701df6af25c6ed4bcd0e045bad3c99c035e63d72/src/utils/Renderer.ts#L32

As you can see here, if you do not provide a `renderer` object to the System or provide a falsy value for `system.renderer.canvas`, the renderer won't have a rendering loop.
